### ISSUE TITLE
Create Stubbed Endpoint

### ISSUE THREAD

**Issue by kjprice** [kjprice/knock-coding-challenge#4]
Knock has a CRM that keeps track of the customers submitting their homes to us. Below is a fictional endpoint that creates a new record with the details about the houses a customer is interested in buying. For this example don't worry about authentication.

### Endpoint

`POST https://knock-crm.io/customer/{:id}/properties`

### Payload

* `mls_name` - (string, required) which mls the property belongs to
* `mls_id` - (number, required) a unique identifier within the mls supplied
* `street_address` - (string, required) the number and street name of the property
* `city` - (string, required) the name of the city the property is in
* `state` - (string, required) the name of the state the property is in
* `zip_code` - (number, required) a 5 digit value for zip code of the property
* `list_price` - (number, required) how much the property is listed for. This should be an integer, example 400000
* `list_date` - (number, required) a Unix timestamp indicating the date the property was listed on. example 1525143600
* `bedrooms` - (number) how many bedrooms the property has
* `full_baths` - (number) how many full bathrooms the property has
* `half_baths` - (number) how many half bathrooms the property has
* `size` - (number) how many square feet the property has

**Comment by kjprice** [comment]
### TODO

- [x] Use Node.js (with express) to create a `set-routes.js` file with a single entry `POST https://knock-crm.io/customer/{:id}/properties`
- [x] For the new route, create a new controller file called `customer.js` with a single function exported called `saveCustomerProperty`
- [x] The function `saveCustomerProperty` will verify that all data from payload is valid and required fields are given 
- [x] Pay special attention to `list_date` which is not a normal number
